In [0]:
import pandas as pd
import random
import numpy as np

from pyspark.sql import SparkSession

In [0]:
spark = SparkSession.builder.appName("Working with Spark").getOrCreate()

# 1. Simple Functions

## Read Data

In [0]:
cases = spark.read.load("/FileStore/tables/Case.csv",format="csv", sep=",", inferSchema="true", header="true")

## Show Data

In [0]:
cases.show()

In [0]:
cases.limit(10).toPandas()

,case_id,province,city,group,infection_case,confirmed,latitude,longitude
0,1000001,Seoul,Yongsan-gu,True,Itaewon Clubs,72,37.538621,126.992652
1,1000002,Seoul,Guro-gu,True,Guro-gu Call Center,98,37.508163,126.884387
2,1000003,Seoul,Dongdaemun-gu,True,Dongan Church,20,37.592888,127.056766
3,1000004,Seoul,Guro-gu,True,Manmin Central Church,41,37.481059,126.894343
4,1000005,Seoul,Eunpyeong-gu,True,Eunpyeong St. Mary's Hospital,14,37.63369,126.9165
5,1000006,Seoul,Seongdong-gu,True,Seongdong-gu APT,13,37.55713,127.0403
6,1000007,Seoul,Jongno-gu,True,Jongno Community Center,10,37.57681,127.006
7,1000008,Seoul,Jung-gu,True,Jung-gu Fashion Company,7,37.562405,126.984377
8,1000009,Seoul,from other city,True,Shincheonji Church,8,-,-
9,1000010,Seoul,-,False,overseas inflow,321,-,-

## Change Column Names

In [0]:
cases = cases.withColumnRenamed("infection_case","infection_source")

In [0]:
cases = cases.toDF(*['case_id', 'province', 'city', 'group', 'infection_case', 'confirmed',
       'latitude', 'longitude'])

## Select Columns

In [0]:
cases = cases.select('province','city','infection_case','confirmed')

In [0]:
cases.show()

+--------+---------------+--------------------+---------+
|province|           city|      infection_case|confirmed|
+--------+---------------+--------------------+---------+
|   Seoul|     Yongsan-gu|       Itaewon Clubs|       72|
|   Seoul|        Guro-gu| Guro-gu Call Center|       98|
|   Seoul|  Dongdaemun-gu|       Dongan Church|       20|
|   Seoul|        Guro-gu|Manmin Central Ch...|       41|
|   Seoul|   Eunpyeong-gu|Eunpyeong St. Mar...|       14|
|   Seoul|   Seongdong-gu|    Seongdong-gu APT|       13|
|   Seoul|      Jongno-gu|Jongno Community ...|       10|
|   Seoul|        Jung-gu|Jung-gu Fashion C...|        7|
|   Seoul|from other city|  Shincheonji Church|        8|
|   Seoul|              -|     overseas inflow|      321|
|   Seoul|              -|contact with patient|       18|
|   Seoul|              -|                 etc|       24|
|   Busan|     Dongnae-gu|       Onchun Church|       39|
|   Busan|from other city|  Shincheonji Church|       12|
|   Busan|     Suyeong-gu|Suyeong-gu Kinder...|        5|
|   Busan|    Haeundae-gu|Haeundae-gu Catho...|        6|
|   Busan|         Jin-gu|      Jin-gu Academy|        4|
|   Busan|from other city|Cheongdo Daenam H...|        1|
|   Busan|              -|     overseas inflow|       25|
|   Busan|              -|contact with patient|       18|
+--------+---------------+--------------------+---------+
only showing top 20 rows

## Sort

In [0]:
cases.sort("confirmed").show()

+-----------------+---------------+--------------------+---------+
|         province|           city|      infection_case|confirmed|
+-----------------+---------------+--------------------+---------+
|          Jeju-do|              -|contact with patient|        0|
|       Gangwon-do|              -|contact with patient|        0|
|          Gwangju|              -|                 etc|        0|
|            Busan|from other city|Cheongdo Daenam H...|        1|
|          Gwangju|              -|contact with patient|        1|
|          Jeju-do|from other city|       Itaewon Clubs|        1|
|           Sejong|from other city|  Shincheonji Church|        1|
|           Sejong|              -|                 etc|        1|
|Chungcheongnam-do|              -|contact with patient|        1|
|     Jeollabuk-do|from other city|  Shincheonji Church|        1|
|     Jeollanam-do|from other city|  Shincheonji Church|        1|
|          Incheon|from other city|  Shincheonji Church|        2|
|     Jeollanam-do|       Muan-gun|Manmin Central Ch...|        2|
|          Daejeon|from other city|  Shincheonji Church|        2|
|     Jeollanam-do|              -|contact with patient|        2|
|            Daegu|from other city|Cheongdo Daenam H...|        2|
|          Daejeon|from other city|Seosan-si Laboratory|        2|
| Gyeongsangnam-do|from other city|       Onchun Church|        2|
|          Daejeon|         Seo-gu|Korea Forest Engi...|        3|
|           Sejong|              -|     overseas inflow|        3|
+-----------------+---------------+--------------------+---------+
only showing top 20 rows

In [0]:
# descending Sort
from pyspark.sql import functions as F
cases.sort(F.desc("confirmed")).show()

+-----------------+---------------+--------------------+---------+
|         province|           city|      infection_case|confirmed|
+-----------------+---------------+--------------------+---------+
|            Daegu|         Nam-gu|  Shincheonji Church|     4510|
|            Daegu|              -|contact with patient|      929|
|            Daegu|              -|                 etc|      724|
| Gyeongsangbuk-do|from other city|  Shincheonji Church|      566|
|            Seoul|              -|     overseas inflow|      321|
|      Gyeonggi-do|              -|     overseas inflow|      225|
|            Daegu|   Dalseong-gun|Second Mi-Ju Hosp...|      196|
| Gyeongsangbuk-do|              -|contact with patient|      192|
| Gyeongsangbuk-do|              -|                 etc|      134|
|            Daegu|         Seo-gu|Hansarang Convale...|      128|
| Gyeongsangbuk-do|   Cheongdo-gun|Cheongdo Daenam H...|      120|
|Chungcheongnam-do|     Cheonan-si|gym facility in C...|      103|
|            Daegu|   Dalseong-gun|Daesil Convalesce...|      100|
|            Seoul|        Guro-gu| Guro-gu Call Center|       98|
|            Seoul|     Yongsan-gu|       Itaewon Clubs|       72|
|      Gyeonggi-do|    Seongnam-si|River of Grace Co...|       72|
| Gyeongsangbuk-do|    Bonghwa-gun|Bonghwa Pureun Nu...|       68|
| Gyeongsangbuk-do|   Gyeongsan-si|Gyeongsan Seorin ...|       66|
|      Gyeonggi-do|              -|contact with patient|       57|
|      Gyeonggi-do|   Uijeongbu-si|Uijeongbu St. Mar...|       50|
+-----------------+---------------+--------------------+---------+
only showing top 20 rows

## Cast

In [0]:
from pyspark.sql.types import IntegerType, StringType, DoubleType

In [0]:
cases = cases.withColumn('confirmed', F.col('confirmed').cast(IntegerType()))
cases = cases.withColumn('city', F.col('city').cast(StringType()))

## Filter

In [0]:
cases.filter((cases.confirmed>10) & (cases.province=='Daegu')).show()

+--------+------------+--------------------+---------+
|province|        city|      infection_case|confirmed|
+--------+------------+--------------------+---------+
|   Daegu|      Nam-gu|  Shincheonji Church|     4510|
|   Daegu|Dalseong-gun|Second Mi-Ju Hosp...|      196|
|   Daegu|      Seo-gu|Hansarang Convale...|      128|
|   Daegu|Dalseong-gun|Daesil Convalesce...|      100|
|   Daegu|     Dong-gu|     Fatima Hospital|       37|
|   Daegu|           -|     overseas inflow|       24|
|   Daegu|           -|contact with patient|      929|
|   Daegu|           -|                 etc|      724|
+--------+------------+--------------------+---------+

## GroupBy

In [0]:
from pyspark.sql import functions as F

cases.groupBy(["province","city"]).agg(F.sum("confirmed") ,F.max("confirmed")).show()

+----------------+---------------+--------------+--------------+
|        province|           city|sum(confirmed)|max(confirmed)|
+----------------+---------------+--------------+--------------+
|Gyeongsangnam-do|       Jinju-si|            10|            10|
|           Seoul|        Guro-gu|           139|            98|
|         Daejeon|              -|            27|            10|
|    Jeollabuk-do|from other city|             1|             1|
|Gyeongsangnam-do|Changnyeong-gun|             7|             7|
|           Seoul|              -|           363|           321|
|         Jeju-do|from other city|             1|             1|
|Gyeongsangbuk-do|              -|           336|           192|
|Gyeongsangnam-do|   Geochang-gun|            18|            10|
|         Incheon|from other city|            22|            20|
|           Busan|              -|            72|            29|
|           Daegu|         Seo-gu|           128|           128|
|           Busan|     Suyeong-gu|             5|             5|
|     Gyeonggi-do|   Uijeongbu-si|            50|            50|
|           Seoul|     Yongsan-gu|            72|            72|
|           Daegu|              -|          1677|           929|
|     Gyeonggi-do|    Seongnam-si|            94|            72|
|Gyeongsangnam-do|from other city|            34|            32|
|     Gyeonggi-do|       Suwon-si|            10|            10|
|         Daejeon|from other city|             4|             2|
+----------------+---------------+--------------+--------------+
only showing top 20 rows

In [0]:
cases.groupBy(["province","city"]).agg(F.sum("confirmed").alias("TotalConfirmed"),F.max("confirmed").alias("MaxFromOneConfirmedCase")).show()

+----------------+---------------+--------------+-----------------------+
|        province|           city|TotalConfirmed|MaxFromOneConfirmedCase|
+----------------+---------------+--------------+-----------------------+
|Gyeongsangnam-do|       Jinju-si|            10|                     10|
|           Seoul|        Guro-gu|           139|                     98|
|         Daejeon|              -|            27|                     10|
|    Jeollabuk-do|from other city|             1|                      1|
|Gyeongsangnam-do|Changnyeong-gun|             7|                      7|
|           Seoul|              -|           363|                    321|
|         Jeju-do|from other city|             1|                      1|
|Gyeongsangbuk-do|              -|           336|                    192|
|Gyeongsangnam-do|   Geochang-gun|            18|                     10|
|         Incheon|from other city|            22|                     20|
|           Busan|              -|            72|                     29|
|           Daegu|         Seo-gu|           128|                    128|
|           Busan|     Suyeong-gu|             5|                      5|
|     Gyeonggi-do|   Uijeongbu-si|            50|                     50|
|           Seoul|     Yongsan-gu|            72|                     72|
|           Daegu|              -|          1677|                    929|
|     Gyeonggi-do|    Seongnam-si|            94|                     72|
|Gyeongsangnam-do|from other city|            34|                     32|
|     Gyeonggi-do|       Suwon-si|            10|                     10|
|         Daejeon|from other city|             4|                      2|
+----------------+---------------+--------------+-----------------------+
only showing top 20 rows

In [0]:
cases.groupBy(["province","city"]).agg(
    F.sum("confirmed").alias("TotalConfirmed"),\
    F.max("confirmed").alias("MaxFromOneConfirmedCase")\
    ).show()

+----------------+---------------+--------------+-----------------------+
|        province|           city|TotalConfirmed|MaxFromOneConfirmedCase|
+----------------+---------------+--------------+-----------------------+
|Gyeongsangnam-do|       Jinju-si|            10|                     10|
|           Seoul|        Guro-gu|           139|                     98|
|         Daejeon|              -|            27|                     10|
|    Jeollabuk-do|from other city|             1|                      1|
|Gyeongsangnam-do|Changnyeong-gun|             7|                      7|
|           Seoul|              -|           363|                    321|
|         Jeju-do|from other city|             1|                      1|
|Gyeongsangbuk-do|              -|           336|                    192|
|Gyeongsangnam-do|   Geochang-gun|            18|                     10|
|         Incheon|from other city|            22|                     20|
|           Busan|              -|            72|                     29|
|           Daegu|         Seo-gu|           128|                    128|
|           Busan|     Suyeong-gu|             5|                      5|
|     Gyeonggi-do|   Uijeongbu-si|            50|                     50|
|           Seoul|     Yongsan-gu|            72|                     72|
|           Daegu|              -|          1677|                    929|
|     Gyeonggi-do|    Seongnam-si|            94|                     72|
|Gyeongsangnam-do|from other city|            34|                     32|
|     Gyeonggi-do|       Suwon-si|            10|                     10|
|         Daejeon|from other city|             4|                      2|
+----------------+---------------+--------------+-----------------------+
only showing top 20 rows

## Joins

In [0]:
regions = spark.read.load("/home/rahul/projects/sparkdf/coronavirusdataset/Region.csv",format="csv", sep=",", inferSchema="true", header="true")
regions.limit(10).toPandas()

,code,province,city,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count
0,10000,Seoul,Seoul,37.566953,126.977977,607,830,48,1.44,15.38,5.8,22739
1,10010,Seoul,Gangnam-gu,37.518421,127.047222,33,38,0,4.18,13.17,4.3,3088
2,10020,Seoul,Gangdong-gu,37.530492,127.123837,27,32,0,1.54,14.55,5.4,1023
3,10030,Seoul,Gangbuk-gu,37.639938,127.025508,14,21,0,0.67,19.49,8.5,628
4,10040,Seoul,Gangseo-gu,37.551166,126.849506,36,56,1,1.17,14.39,5.7,1080
5,10050,Seoul,Gwanak-gu,37.478290,126.951502,22,33,1,0.89,15.12,4.9,909
6,10060,Seoul,Gwangjin-gu,37.538712,127.082366,22,33,3,1.16,13.75,4.8,723
7,10070,Seoul,Guro-gu,37.495632,126.887650,26,34,3,1.00,16.21,5.7,741
8,10080,Seoul,Geumcheon-gu,37.456852,126.895229,18,19,0,0.96,16.15,6.7,475
9,10090,Seoul,Nowon-gu,37.654259,127.056294,42,66,6,1.39,15.40,7.4,952

In [0]:
cases = cases.join(regions, ['province','city'],how='left')

In [0]:
cases.limit(10).toPandas()

,province,city,infection_case,confirmed,code,latitude,longitude,elementary_school_count,kindergarten_count,university_count,academy_ratio,elderly_population_ratio,elderly_alone_ratio,nursing_home_count
0,Seoul,Yongsan-gu,Itaewon Clubs,72,10210.0,37.532768,126.990021,15.0,13.0,1.0,0.68,16.87,6.5,435.0
1,Seoul,Guro-gu,Guro-gu Call Center,98,10070.0,37.495632,126.887650,26.0,34.0,3.0,1.00,16.21,5.7,741.0
2,Seoul,Dongdaemun-gu,Dongan Church,20,10110.0,37.574552,127.039721,21.0,31.0,4.0,1.06,17.26,6.7,832.0
3,Seoul,Guro-gu,Manmin Central Church,41,10070.0,37.495632,126.887650,26.0,34.0,3.0,1.00,16.21,5.7,741.0
4,Seoul,Eunpyeong-gu,Eunpyeong St. Mary's Hospital,14,10220.0,37.603481,126.929173,31.0,44.0,1.0,1.09,17.00,6.5,874.0
5,Seoul,Seongdong-gu,Seongdong-gu APT,13,10160.0,37.563277,127.036647,21.0,30.0,2.0,0.97,14.76,5.3,593.0
6,Seoul,Jongno-gu,Jongno Community Center,10,10230.0,37.572999,126.979189,13.0,17.0,3.0,1.71,18.27,6.8,668.0
7,Seoul,Jung-gu,Jung-gu Fashion Company,7,10240.0,37.563988,126.997530,12.0,14.0,2.0,0.94,18.42,7.4,728.0
8,Seoul,from other city,Shincheonji Church,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Seoul,-,overseas inflow,321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 2. Broadcast/Map Side Joins

In [0]:
big = pd.DataFrame({'A':[1,1,1,1,2,2,2,2],'price': [i for i in range(8)]}) 

small = pd.DataFrame({'A':[1,1,1,1,2,2],'agg':['sum','mean','max','min','sum','mean']})

In [0]:
big

,A,price
0,1,0
1,1,1
2,1,2
3,1,3
4,2,4
5,2,5
6,2,6
7,2,7

In [0]:
small

,A,agg
0,1,sum
1,1,mean
2,1,max
3,1,min
4,2,sum
5,2,mean

In [0]:
big.merge(small,on = ['A'],how='left')

,A,price,agg
0,1,0,sum
1,1,0,mean
2,1,0,max
3,1,0,min
4,1,1,sum
5,1,1,mean
6,1,1,max
7,1,1,min
8,1,2,sum
9,1,2,mean
10,1,2,max
11,1,2,min
12,1,3,sum
13,1,3,mean
14,1,3,max
15,1,3,min
16,2,4,sum
17,2,4,mean
18,2,5,sum
19,2,5,mean
20,2,6,sum
21,2,6,mean
22,2,7,sum
23,2,7,mean

Such sort of operations is aplenty in Spark where you might want to apply multiple operations to a particular key. But assuming that the key data in the Big table is large, it will involve a lot of data movement. And sometimes so much that the application itself breaks. A small optimization then you can do when joining on such big tables(assuming the other table is small) is to broadcast the small table to each machine when you perform a join. You can do this easily using the broadcast keyword.

In [0]:
from pyspark.sql.functions import broadcast
cases = cases.join(broadcast(regions), ['province','city'],how='left')

In [0]:
cases

Out[28]: DataFrame[province: string, city: string, infection_case: string, confirmed: int, code: int, latitude: double, longitude: double, elementary_school_count: int, kindergarten_count: int, university_count: int, academy_ratio: double, elderly_population_ratio: double, elderly_alone_ratio: double, nursing_home_count: int, code: int, latitude: double, longitude: double, elementary_school_count: int, kindergarten_count: int, university_count: int, academy_ratio: double, elderly_population_ratio: double, elderly_alone_ratio: double, nursing_home_count: int]

# 3. Using SQL with Spark

In [0]:
# Reading Original Cases Back again
cases = spark.read.load("/home/rahul/projects/sparkdf/coronavirusdataset/Case.csv",format="csv", sep=",", inferSchema="true", header="true")

In [0]:
cases.registerTempTable('cases_table')
newDF = sqlContext.sql('select * from cases_table where confirmed>100')

In [0]:
newDF.show()

+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+
|case_id|         province|           city|group|      infection_case|confirmed| latitude| longitude|
+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+
|1000010|            Seoul|              -|false|     overseas inflow|      321|        -|         -|
|1200001|            Daegu|         Nam-gu| true|  Shincheonji Church|     4510| 35.84008|  128.5667|
|1200002|            Daegu|   Dalseong-gun| true|Second Mi-Ju Hosp...|      196|35.857375|128.466651|
|1200003|            Daegu|         Seo-gu| true|Hansarang Convale...|      128|35.885592|128.556649|
|1200008|            Daegu|              -|false|contact with patient|      929|        -|         -|
|1200009|            Daegu|              -|false|                 etc|      724|        -|         -|
|2000007|      Gyeonggi-do|              -|false|     overseas inflow|      225|        -|         -|
|4100001|Chungcheongnam-do|     Cheonan-si| true|gym facility in C...|      103| 36.81503|  127.1139|
|6000001| Gyeongsangbuk-do|from other city| true|  Shincheonji Church|      566|        -|         -|
|6000002| Gyeongsangbuk-do|   Cheongdo-gun| true|Cheongdo Daenam H...|      120| 35.64887|  128.7368|
|6000011| Gyeongsangbuk-do|              -|false|contact with patient|      192|        -|         -|
|6000012| Gyeongsangbuk-do|              -|false|                 etc|      134|        -|         -|
+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+

# 4. Create New Columns

## Using Spark Native Functions

In [0]:
casesWithNewConfirmed = cases.withColumn("NewConfirmed", 100 + F.col("confirmed"))
casesWithNewConfirmed.show()

+-------+--------+---------------+-----+--------------------+---------+---------+----------+------------+
|case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|NewConfirmed|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+------------+
|1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|       72|37.538621|126.992652|         172|
|1000002|   Seoul|        Guro-gu| true| Guro-gu Call Center|       98|37.508163|126.884387|         198|
|1000003|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       20|37.592888|127.056766|         120|
|1000004|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|         141|
|1000005|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|         114|
|1000006|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|         113|
|1000007|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|         110|
|1000008|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|         107|
|1000009|   Seoul|from other city| true|  Shincheonji Church|        8|        -|         -|         108|
|1000010|   Seoul|              -|false|     overseas inflow|      321|        -|         -|         421|
|1000011|   Seoul|              -|false|contact with patient|       18|        -|         -|         118|
|1000012|   Seoul|              -|false|                 etc|       24|        -|         -|         124|
|1100001|   Busan|     Dongnae-gu| true|       Onchun Church|       39| 35.21628|  129.0771|         139|
|1100002|   Busan|from other city| true|  Shincheonji Church|       12|        -|         -|         112|
|1100003|   Busan|     Suyeong-gu| true|Suyeong-gu Kinder...|        5| 35.16708|  129.1124|         105|
|1100004|   Busan|    Haeundae-gu| true|Haeundae-gu Catho...|        6| 35.20599|  129.1256|         106|
|1100005|   Busan|         Jin-gu| true|      Jin-gu Academy|        4| 35.17371|  129.0633|         104|
|1100006|   Busan|from other city| true|Cheongdo Daenam H...|        1|        -|         -|         101|
|1100007|   Busan|              -|false|     overseas inflow|       25|        -|         -|         125|
|1100008|   Busan|              -|false|contact with patient|       18|        -|         -|         118|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+------------+
only showing top 20 rows

In [0]:
casesWithExpConfirmed = cases.withColumn("ExpConfirmed", F.exp("confirmed"))
casesWithExpConfirmed.show()

+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
|case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|        ExpConfirmed|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
|1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|       72|37.538621|126.992652|1.858671745284127...|
|1000002|   Seoul|        Guro-gu| true| Guro-gu Call Center|       98|37.508163|126.884387|3.637970947608805E42|
|1000003|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       20|37.592888|127.056766| 4.851651954097903E8|
|1000004|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|6.398434935300549...|
|1000005|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|  1202604.2841647768|
|1000006|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|   442413.3920089205|
|1000007|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|  22026.465794806718|
|1000008|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|  1096.6331584284585|
|1000009|   Seoul|from other city| true|  Shincheonji Church|        8|        -|         -|  2980.9579870417283|
|1000010|   Seoul|              -|false|     overseas inflow|      321|        -|         -|2.56170249311968E139|
|1000011|   Seoul|              -|false|contact with patient|       18|        -|         -| 6.565996913733051E7|
|1000012|   Seoul|              -|false|                 etc|       24|        -|         -|2.648912212984347E10|
|1100001|   Busan|     Dongnae-gu| true|       Onchun Church|       39| 35.21628|  129.0771|8.659340042399374...|
|1100002|   Busan|from other city| true|  Shincheonji Church|       12|        -|         -|  162754.79141900392|
|1100003|   Busan|     Suyeong-gu| true|Suyeong-gu Kinder...|        5| 35.16708|  129.1124|   148.4131591025766|
|1100004|   Busan|    Haeundae-gu| true|Haeundae-gu Catho...|        6| 35.20599|  129.1256|   403.4287934927351|
|1100005|   Busan|         Jin-gu| true|      Jin-gu Academy|        4| 35.17371|  129.0633|  54.598150033144236|
|1100006|   Busan|from other city| true|Cheongdo Daenam H...|        1|        -|         -|   2.718281828459045|
|1100007|   Busan|              -|false|     overseas inflow|       25|        -|         -|7.200489933738588E10|
|1100008|   Busan|              -|false|contact with patient|       18|        -|         -| 6.565996913733051E7|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
only showing top 20 rows

## Spark UDFs

In [0]:
import pyspark.sql.functions as F
from pyspark.sql.types import *
def casesHighLow(confirmed):
    if confirmed < 50: 
        return 'low'
    else:
        return 'high'
    
#convert to a UDF Function by passing in the function and return type of function
casesHighLowUDF = F.udf(casesHighLow, StringType())

CasesWithHighLow = cases.withColumn("HighLow", casesHighLowUDF("confirmed"))
CasesWithHighLow.show()

+-------+--------+---------------+-----+--------------------+---------+---------+----------+-------+
|case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|HighLow|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+-------+
|1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|       72|37.538621|126.992652|   high|
|1000002|   Seoul|        Guro-gu| true| Guro-gu Call Center|       98|37.508163|126.884387|   high|
|1000003|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       20|37.592888|127.056766|    low|
|1000004|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|    low|
|1000005|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|    low|
|1000006|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|    low|
|1000007|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|    low|
|1000008|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|    low|
|1000009|   Seoul|from other city| true|  Shincheonji Church|        8|        -|         -|    low|
|1000010|   Seoul|              -|false|     overseas inflow|      321|        -|         -|   high|
|1000011|   Seoul|              -|false|contact with patient|       18|        -|         -|    low|
|1000012|   Seoul|              -|false|                 etc|       24|        -|         -|    low|
|1100001|   Busan|     Dongnae-gu| true|       Onchun Church|       39| 35.21628|  129.0771|    low|
|1100002|   Busan|from other city| true|  Shincheonji Church|       12|        -|         -|    low|
|1100003|   Busan|     Suyeong-gu| true|Suyeong-gu Kinder...|        5| 35.16708|  129.1124|    low|
|1100004|   Busan|    Haeundae-gu| true|Haeundae-gu Catho...|        6| 35.20599|  129.1256|    low|
|1100005|   Busan|         Jin-gu| true|      Jin-gu Academy|        4| 35.17371|  129.0633|    low|
|1100006|   Busan|from other city| true|Cheongdo Daenam H...|        1|        -|         -|    low|
|1100007|   Busan|              -|false|     overseas inflow|       25|        -|         -|    low|
|1100008|   Busan|              -|false|contact with patient|       18|        -|         -|    low|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+-------+
only showing top 20 rows

## Using RDDs

In [0]:
import math
from pyspark.sql import Row
def rowwise_function(row):
    # convert row to python dictionary:
    row_dict = row.asDict()
    # Add a new key in the dictionary with the new column name and value.
    # This might be a big complex function.
    row_dict['expConfirmed'] = float(np.exp(row_dict['confirmed']))
    # convert dict to row back again:
    newrow = Row(**row_dict)
    # return new row
    return newrow

# convert cases dataframe to RDD
cases_rdd = cases.rdd

# apply our function to RDD
cases_rdd_new = cases_rdd.map(lambda row: rowwise_function(row))

# Convert RDD Back to DataFrame
casesNewDf = sqlContext.createDataFrame(cases_rdd_new)

casesNewDf.show()

+-------+---------------+---------+--------------------+-----+--------------------+---------+----------+--------+
|case_id|           city|confirmed|        expConfirmed|group|      infection_case| latitude| longitude|province|
+-------+---------------+---------+--------------------+-----+--------------------+---------+----------+--------+
|1000001|     Yongsan-gu|       72|1.858671745284127...| true|       Itaewon Clubs|37.538621|126.992652|   Seoul|
|1000002|        Guro-gu|       98|3.637970947608805E42| true| Guro-gu Call Center|37.508163|126.884387|   Seoul|
|1000003|  Dongdaemun-gu|       20| 4.851651954097903E8| true|       Dongan Church|37.592888|127.056766|   Seoul|
|1000004|        Guro-gu|       41|6.398434935300549...| true|Manmin Central Ch...|37.481059|126.894343|   Seoul|
|1000005|   Eunpyeong-gu|       14|  1202604.2841647768| true|Eunpyeong St. Mar...| 37.63369|  126.9165|   Seoul|
|1000006|   Seongdong-gu|       13|   442413.3920089205| true|    Seongdong-gu APT| 37.55713|  127.0403|   Seoul|
|1000007|      Jongno-gu|       10|  22026.465794806718| true|Jongno Community ...| 37.57681|   127.006|   Seoul|
|1000008|        Jung-gu|        7|  1096.6331584284585| true|Jung-gu Fashion C...|37.562405|126.984377|   Seoul|
|1000009|from other city|        8|  2980.9579870417283| true|  Shincheonji Church|        -|         -|   Seoul|
|1000010|              -|      321|2.56170249311968E139|false|     overseas inflow|        -|         -|   Seoul|
|1000011|              -|       18| 6.565996913733051E7|false|contact with patient|        -|         -|   Seoul|
|1000012|              -|       24|2.648912212984347E10|false|                 etc|        -|         -|   Seoul|
|1100001|     Dongnae-gu|       39|8.659340042399374...| true|       Onchun Church| 35.21628|  129.0771|   Busan|
|1100002|from other city|       12|  162754.79141900392| true|  Shincheonji Church|        -|         -|   Busan|
|1100003|     Suyeong-gu|        5|   148.4131591025766| true|Suyeong-gu Kinder...| 35.16708|  129.1124|   Busan|
|1100004|    Haeundae-gu|        6|   403.4287934927351| true|Haeundae-gu Catho...| 35.20599|  129.1256|   Busan|
|1100005|         Jin-gu|        4|  54.598150033144236| true|      Jin-gu Academy| 35.17371|  129.0633|   Busan|
|1100006|from other city|        1|   2.718281828459045| true|Cheongdo Daenam H...|        -|         -|   Busan|
|1100007|              -|       25|7.200489933738588E10|false|     overseas inflow|        -|         -|   Busan|
|1100008|              -|       18| 6.565996913733051E7|false|contact with patient|        -|         -|   Busan|
+-------+---------------+---------+--------------------+-----+--------------------+---------+----------+--------+
only showing top 20 rows

## Pandas UDF

In [0]:
cases.printSchema()

root
 |-- case_id: integer (nullable = true)
 |-- province: string (nullable = true)
 |-- city: string (nullable = true)
 |-- group: boolean (nullable = true)
 |-- infection_case: string (nullable = true)
 |-- confirmed: integer (nullable = true)
 |-- latitude: string (nullable = true)
 |-- longitude: string (nullable = true)

In [0]:
from pyspark.sql.types import IntegerType, StringType, DoubleType, BooleanType
from pyspark.sql.types import StructType, StructField

# Declare the schema for the output of our function

outSchema = StructType([StructField('case_id',IntegerType(),True),
                        StructField('province',StringType(),True),
                        StructField('city',StringType(),True),
                        StructField('group',BooleanType(),True),
                        StructField('infection_case',StringType(),True),
                        StructField('confirmed',IntegerType(),True),
                        StructField('latitude',StringType(),True),
                        StructField('longitude',StringType(),True),
                        StructField('normalized_confirmed',DoubleType(),True)
                       ])
# decorate our function with pandas_udf decorator
@F.pandas_udf(outSchema, F.PandasUDFType.GROUPED_MAP)
def subtract_mean(pdf):
    # pdf is a pandas.DataFrame
    v = pdf.confirmed
    v = v - v.mean()
    pdf['normalized_confirmed'] = v
    return pdf

confirmed_groupwise_normalization = cases.groupby("infection_case").apply(subtract_mean)

confirmed_groupwise_normalization.limit(10).toPandas()

,case_id,province,city,group,infection_case,confirmed,latitude,longitude,normalized_confirmed
0,1000005,Seoul,Eunpyeong-gu,True,Eunpyeong St. Mary's Hospital,14,37.63369,126.9165,0.000000
1,1700001,Sejong,Sejong,True,Ministry of Oceans and Fisheries,30,36.504713,127.265172,0.000000
2,2000005,Gyeonggi-do,Seongnam-si,True,Bundang Jesaeng Hospital,22,37.38833,127.1218,0.000000
3,6000005,Gyeongsangbuk-do,Chilgok-gun,True,Milal Shelter,36,36.0581,128.4941,0.000000
4,1000001,Seoul,Yongsan-gu,True,Itaewon Clubs,72,37.538621,126.992652,45.000000
5,2000010,Gyeonggi-do,from other city,True,Itaewon Clubs,8,-,-,-19.000000
6,7000004,Jeju-do,from other city,True,Itaewon Clubs,1,-,-,-26.000000
7,3000003,Gangwon-do,Wonju-si,True,Wonju-si Apartments,3,37.342762,127.983815,0.000000
8,1000003,Seoul,Dongdaemun-gu,True,Dongan Church,20,37.592888,127.056766,0.000000
9,1000010,Seoul,-,False,overseas inflow,321,-,-,275.294118

# 5. Spark Window Functions

In [0]:
timeprovince = spark.read.load("/home/rahul/projects/sparkdf/coronavirusdataset/TimeProvince.csv",format="csv", \
                        sep=",", inferSchema="true", header="true")
timeprovince.show()

+-------------------+----+-----------------+---------+--------+--------+
|               date|time|         province|confirmed|released|deceased|
+-------------------+----+-----------------+---------+--------+--------+
|2020-01-20 00:00:00|  16|            Seoul|        0|       0|       0|
|2020-01-20 00:00:00|  16|            Busan|        0|       0|       0|
|2020-01-20 00:00:00|  16|            Daegu|        0|       0|       0|
|2020-01-20 00:00:00|  16|          Incheon|        1|       0|       0|
|2020-01-20 00:00:00|  16|          Gwangju|        0|       0|       0|
|2020-01-20 00:00:00|  16|          Daejeon|        0|       0|       0|
|2020-01-20 00:00:00|  16|            Ulsan|        0|       0|       0|
|2020-01-20 00:00:00|  16|           Sejong|        0|       0|       0|
|2020-01-20 00:00:00|  16|      Gyeonggi-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|       Gangwon-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|Chungcheongbuk-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|Chungcheongnam-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|     Jeollabuk-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|     Jeollanam-do|        0|       0|       0|
|2020-01-20 00:00:00|  16| Gyeongsangbuk-do|        0|       0|       0|
|2020-01-20 00:00:00|  16| Gyeongsangnam-do|        0|       0|       0|
|2020-01-20 00:00:00|  16|          Jeju-do|        0|       0|       0|
|2020-01-21 00:00:00|  16|            Seoul|        0|       0|       0|
|2020-01-21 00:00:00|  16|            Busan|        0|       0|       0|
|2020-01-21 00:00:00|  16|            Daegu|        0|       0|       0|
+-------------------+----+-----------------+---------+--------+--------+
only showing top 20 rows

# Ranking

In [0]:
from pyspark.sql.window import Window
windowSpec = Window().partitionBy(['province']).orderBy(F.desc('confirmed'))
cases.withColumn("rank",F.rank().over(windowSpec)).show()

+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+----+
|case_id|         province|           city|group|      infection_case|confirmed| latitude| longitude|rank|
+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+----+
|1700001|           Sejong|         Sejong| true|Ministry of Ocean...|       30|36.504713|127.265172|   1|
|1700002|           Sejong|         Sejong| true|gym facility in S...|        8| 36.48025|   127.289|   2|
|1700004|           Sejong|              -|false|     overseas inflow|        3|        -|         -|   3|
|1700005|           Sejong|              -|false|contact with patient|        3|        -|         -|   3|
|1700003|           Sejong|from other city| true|  Shincheonji Church|        1|        -|         -|   5|
|1700006|           Sejong|              -|false|                 etc|        1|        -|         -|   5|
|1600001|            Ulsan|from other city| true|  Shincheonji Church|       16|        -|         -|   1|
|1600002|            Ulsan|              -|false|     overseas inflow|       15|        -|         -|   2|
|1600004|            Ulsan|              -|false|                 etc|        7|        -|         -|   3|
|1600003|            Ulsan|              -|false|contact with patient|        4|        -|         -|   4|
|4000002|Chungcheongbuk-do|     Goesan-gun| true|Goesan-gun Jangye...|       11| 36.82422|  127.9552|   1|
|4000005|Chungcheongbuk-do|              -|false|                 etc|        8|        -|         -|   2|
|4000003|Chungcheongbuk-do|              -|false|     overseas inflow|        7|        -|         -|   3|
|4000001|Chungcheongbuk-do|from other city| true|  Shincheonji Church|        6|        -|         -|   4|
|4000004|Chungcheongbuk-do|              -|false|contact with patient|        6|        -|         -|   4|
|3000001|       Gangwon-do|from other city| true|  Shincheonji Church|       17|        -|         -|   1|
|3000004|       Gangwon-do|              -|false|     overseas inflow|       14|        -|         -|   2|
|3000002|       Gangwon-do|from other city| true|Uijeongbu St. Mar...|       10|        -|         -|   3|
|3000006|       Gangwon-do|              -|false|                 etc|        7|        -|         -|   4|
|3000003|       Gangwon-do|       Wonju-si| true| Wonju-si Apartments|        3|37.342762|127.983815|   5|
+-------+-----------------+---------------+-----+--------------------+---------+---------+----------+----+
only showing top 20 rows

# Lag

In [0]:
from pyspark.sql.window import Window
windowSpec = Window().partitionBy(['province']).orderBy('date')
timeprovinceWithLag = timeprovince.withColumn("lag_7",F.lag("confirmed", 7).over(windowSpec))

timeprovinceWithLag.filter(timeprovinceWithLag.date>'2020-03-10').show()

+-------------------+----+--------+---------+--------+--------+-----+
|               date|time|province|confirmed|released|deceased|lag_7|
+-------------------+----+--------+---------+--------+--------+-----+
|2020-03-10 00:00:00|   0|  Sejong|        8|       0|       0|    1|
|2020-03-11 00:00:00|   0|  Sejong|       10|       0|       0|    1|
|2020-03-12 00:00:00|   0|  Sejong|       15|       0|       0|    1|
|2020-03-13 00:00:00|   0|  Sejong|       32|       0|       0|    1|
|2020-03-14 00:00:00|   0|  Sejong|       38|       0|       0|    2|
|2020-03-15 00:00:00|   0|  Sejong|       39|       0|       0|    3|
|2020-03-16 00:00:00|   0|  Sejong|       40|       0|       0|    6|
|2020-03-17 00:00:00|   0|  Sejong|       40|       0|       0|    8|
|2020-03-18 00:00:00|   0|  Sejong|       41|       0|       0|   10|
|2020-03-19 00:00:00|   0|  Sejong|       41|       0|       0|   15|
|2020-03-20 00:00:00|   0|  Sejong|       41|       0|       0|   32|
|2020-03-21 00:00:00|   0|  Sejong|       41|       2|       0|   38|
|2020-03-22 00:00:00|   0|  Sejong|       41|       3|       0|   39|
|2020-03-23 00:00:00|   0|  Sejong|       42|       3|       0|   40|
|2020-03-24 00:00:00|   0|  Sejong|       42|       3|       0|   40|
|2020-03-25 00:00:00|   0|  Sejong|       44|       3|       0|   41|
|2020-03-26 00:00:00|   0|  Sejong|       44|       8|       0|   41|
|2020-03-27 00:00:00|   0|  Sejong|       44|       9|       0|   41|
|2020-03-28 00:00:00|   0|  Sejong|       44|       9|       0|   41|
|2020-03-29 00:00:00|   0|  Sejong|       46|      11|       0|   41|
+-------------------+----+--------+---------+--------+--------+-----+
only showing top 20 rows

# Rolling Aggregations

In [0]:
from pyspark.sql.window import Window

windowSpec = Window().partitionBy(['province']).orderBy('date').rowsBetween(-6,0)
timeprovinceWithRoll = timeprovince.withColumn("roll_7_confirmed",F.mean("confirmed").over(windowSpec))
timeprovinceWithRoll.filter(timeprovinceWithLag.date>'2020-03-10').show()

+-------------------+----+--------+---------+--------+--------+------------------+
|               date|time|province|confirmed|released|deceased|  roll_7_confirmed|
+-------------------+----+--------+---------+--------+--------+------------------+
|2020-03-10 00:00:00|   0|  Sejong|        8|       0|       0| 3.142857142857143|
|2020-03-11 00:00:00|   0|  Sejong|       10|       0|       0| 4.428571428571429|
|2020-03-12 00:00:00|   0|  Sejong|       15|       0|       0| 6.428571428571429|
|2020-03-13 00:00:00|   0|  Sejong|       32|       0|       0|10.857142857142858|
|2020-03-14 00:00:00|   0|  Sejong|       38|       0|       0|              16.0|
|2020-03-15 00:00:00|   0|  Sejong|       39|       0|       0|21.142857142857142|
|2020-03-16 00:00:00|   0|  Sejong|       40|       0|       0|              26.0|
|2020-03-17 00:00:00|   0|  Sejong|       40|       0|       0|30.571428571428573|
|2020-03-18 00:00:00|   0|  Sejong|       41|       0|       0|              35.0|
|2020-03-19 00:00:00|   0|  Sejong|       41|       0|       0|38.714285714285715|
|2020-03-20 00:00:00|   0|  Sejong|       41|       0|       0|              40.0|
|2020-03-21 00:00:00|   0|  Sejong|       41|       2|       0| 40.42857142857143|
|2020-03-22 00:00:00|   0|  Sejong|       41|       3|       0|40.714285714285715|
|2020-03-23 00:00:00|   0|  Sejong|       42|       3|       0|              41.0|
|2020-03-24 00:00:00|   0|  Sejong|       42|       3|       0|41.285714285714285|
|2020-03-25 00:00:00|   0|  Sejong|       44|       3|       0|41.714285714285715|
|2020-03-26 00:00:00|   0|  Sejong|       44|       8|       0|42.142857142857146|
|2020-03-27 00:00:00|   0|  Sejong|       44|       9|       0| 42.57142857142857|
|2020-03-28 00:00:00|   0|  Sejong|       44|       9|       0|              43.0|
|2020-03-29 00:00:00|   0|  Sejong|       46|      11|       0|43.714285714285715|
+-------------------+----+--------+---------+--------+--------+------------------+
only showing top 20 rows

## Running Totals

In [0]:
from pyspark.sql.window import Window

windowSpec = Window().partitionBy(['province']).orderBy('date').rowsBetween(Window.unboundedPreceding,Window.currentRow)
timeprovinceWithRoll = timeprovince.withColumn("cumulative_confirmed",F.sum("confirmed").over(windowSpec))
timeprovinceWithRoll.filter(timeprovinceWithLag.date>'2020-03-10').show()

+-------------------+----+--------+---------+--------+--------+--------------------+
|               date|time|province|confirmed|released|deceased|cumulative_confirmed|
+-------------------+----+--------+---------+--------+--------+--------------------+
|2020-03-10 00:00:00|   0|  Sejong|        8|       0|       0|                  33|
|2020-03-11 00:00:00|   0|  Sejong|       10|       0|       0|                  43|
|2020-03-12 00:00:00|   0|  Sejong|       15|       0|       0|                  58|
|2020-03-13 00:00:00|   0|  Sejong|       32|       0|       0|                  90|
|2020-03-14 00:00:00|   0|  Sejong|       38|       0|       0|                 128|
|2020-03-15 00:00:00|   0|  Sejong|       39|       0|       0|                 167|
|2020-03-16 00:00:00|   0|  Sejong|       40|       0|       0|                 207|
|2020-03-17 00:00:00|   0|  Sejong|       40|       0|       0|                 247|
|2020-03-18 00:00:00|   0|  Sejong|       41|       0|       0|                 288|
|2020-03-19 00:00:00|   0|  Sejong|       41|       0|       0|                 329|
|2020-03-20 00:00:00|   0|  Sejong|       41|       0|       0|                 370|
|2020-03-21 00:00:00|   0|  Sejong|       41|       2|       0|                 411|
|2020-03-22 00:00:00|   0|  Sejong|       41|       3|       0|                 452|
|2020-03-23 00:00:00|   0|  Sejong|       42|       3|       0|                 494|
|2020-03-24 00:00:00|   0|  Sejong|       42|       3|       0|                 536|
|2020-03-25 00:00:00|   0|  Sejong|       44|       3|       0|                 580|
|2020-03-26 00:00:00|   0|  Sejong|       44|       8|       0|                 624|
|2020-03-27 00:00:00|   0|  Sejong|       44|       9|       0|                 668|
|2020-03-28 00:00:00|   0|  Sejong|       44|       9|       0|                 712|
|2020-03-29 00:00:00|   0|  Sejong|       46|      11|       0|                 758|
+-------------------+----+--------+---------+--------+--------+--------------------+
only showing top 20 rows

# 6. Pivot Dataframes

In [0]:
pivotedTimeprovince = timeprovince.groupBy('date').pivot('province') \
                      .agg(F.sum('confirmed').alias('confirmed') , F.sum('released').alias('released'))
pivotedTimeprovince.limit(10).toPandas()

,date,Busan_confirmed,Busan_released,Chungcheongbuk-do_confirmed,Chungcheongbuk-do_released,Chungcheongnam-do_confirmed,Chungcheongnam-do_released,Daegu_confirmed,Daegu_released,Daejeon_confirmed,...,Jeollabuk-do_confirmed,Jeollabuk-do_released,Jeollanam-do_confirmed,Jeollanam-do_released,Sejong_confirmed,Sejong_released,Seoul_confirmed,Seoul_released,Ulsan_confirmed,Ulsan_released
0,2020-02-02,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,5,0,0,0
1,2020-04-19,130,115,45,38,141,122,6832,5743,39,...,17,9,15,8,46,29,624,288,42,34
2,2020-03-04,92,2,11,0,82,0,4007,11,15,...,7,1,4,0,1,0,99,19,23,0
3,2020-01-31,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,4,0,0,0
4,2020-04-17,130,112,45,37,139,115,6827,5626,40,...,17,9,15,7,46,24,621,268,42,34
5,2020-02-22,11,0,3,0,1,0,193,0,2,...,3,1,1,0,1,0,30,6,1,0
6,2020-04-11,126,100,45,28,138,106,6814,5271,39,...,17,8,15,5,46,20,599,195,41,30
7,2020-05-11,141,125,52,42,143,134,6861,6318,41,...,19,14,16,12,47,45,683,545,44,38
8,2020-03-16,107,53,31,6,115,12,6066,734,22,...,7,4,4,2,40,0,253,52,28,7
9,2020-01-20,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# 7. Unpivot/Stack Dataframes

In [0]:
pivotedTimeprovince.columns

Out[44]: ['date',
 'Busan_confirmed',
 'Busan_released',
 'Chungcheongbuk-do_confirmed',
 'Chungcheongbuk-do_released',
 'Chungcheongnam-do_confirmed',
 'Chungcheongnam-do_released',
 'Daegu_confirmed',
 'Daegu_released',
 'Daejeon_confirmed',
 'Daejeon_released',
 'Gangwon-do_confirmed',
 'Gangwon-do_released',
 'Gwangju_confirmed',
 'Gwangju_released',
 'Gyeonggi-do_confirmed',
 'Gyeonggi-do_released',
 'Gyeongsangbuk-do_confirmed',
 'Gyeongsangbuk-do_released',
 'Gyeongsangnam-do_confirmed',
 'Gyeongsangnam-do_released',
 'Incheon_confirmed',
 'Incheon_released',
 'Jeju-do_confirmed',
 'Jeju-do_released',
 'Jeollabuk-do_confirmed',
 'Jeollabuk-do_released',
 'Jeollanam-do_confirmed',
 'Jeollanam-do_released',
 'Sejong_confirmed',
 'Sejong_released',
 'Seoul_confirmed',
 'Seoul_released',
 'Ulsan_confirmed',
 'Ulsan_released']

In [0]:
newColnames = [x.replace("-","_") for x in pivotedTimeprovince.columns]

In [0]:
pivotedTimeprovince = pivotedTimeprovince.toDF(*newColnames)

In [0]:
expression = ""
cnt=0
for column in pivotedTimeprovince.columns:
    if column!='date':
        cnt +=1
        expression += f"'{column}' , {column},"
        
expression = f"stack({cnt}, {expression[:-1]}) as (Type,Value)"

In [0]:
unpivotedTimeprovince = pivotedTimeprovince.select('date',F.expr(expression))
unpivotedTimeprovince.show()

+-------------------+--------------------+-----+
|               date|                Type|Value|
+-------------------+--------------------+-----+
|2020-02-02 00:00:00|     Busan_confirmed|    0|
|2020-02-02 00:00:00|      Busan_released|    0|
|2020-02-02 00:00:00|Chungcheongbuk_do...|    0|
|2020-02-02 00:00:00|Chungcheongbuk_do...|    0|
|2020-02-02 00:00:00|Chungcheongnam_do...|    0|
|2020-02-02 00:00:00|Chungcheongnam_do...|    0|
|2020-02-02 00:00:00|     Daegu_confirmed|    0|
|2020-02-02 00:00:00|      Daegu_released|    0|
|2020-02-02 00:00:00|   Daejeon_confirmed|    0|
|2020-02-02 00:00:00|    Daejeon_released|    0|
|2020-02-02 00:00:00|Gangwon_do_confirmed|    0|
|2020-02-02 00:00:00| Gangwon_do_released|    0|
|2020-02-02 00:00:00|   Gwangju_confirmed|    0|
|2020-02-02 00:00:00|    Gwangju_released|    0|
|2020-02-02 00:00:00|Gyeonggi_do_confi...|    8|
|2020-02-02 00:00:00|Gyeonggi_do_released|    0|
|2020-02-02 00:00:00|Gyeongsangbuk_do_...|    0|
|2020-02-02 00:00:00|Gyeongsangbuk_do_...|    0|
|2020-02-02 00:00:00|Gyeongsangnam_do_...|    0|
|2020-02-02 00:00:00|Gyeongsangnam_do_...|    0|
+-------------------+--------------------+-----+
only showing top 20 rows

# 8. Salting

In [0]:
cases = cases.withColumn("salt_key", F.concat(F.col("infection_case"), F.lit("_"), F.monotonically_increasing_id() % 10))

In [0]:
cases.show()

+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
|case_id|province|           city|group|      infection_case|confirmed| latitude| longitude|            salt_key|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
|1000001|   Seoul|     Yongsan-gu| true|       Itaewon Clubs|       72|37.538621|126.992652|     Itaewon Clubs_0|
|1000002|   Seoul|        Guro-gu| true| Guro-gu Call Center|       98|37.508163|126.884387|Guro-gu Call Cent...|
|1000003|   Seoul|  Dongdaemun-gu| true|       Dongan Church|       20|37.592888|127.056766|     Dongan Church_2|
|1000004|   Seoul|        Guro-gu| true|Manmin Central Ch...|       41|37.481059|126.894343|Manmin Central Ch...|
|1000005|   Seoul|   Eunpyeong-gu| true|Eunpyeong St. Mar...|       14| 37.63369|  126.9165|Eunpyeong St. Mar...|
|1000006|   Seoul|   Seongdong-gu| true|    Seongdong-gu APT|       13| 37.55713|  127.0403|  Seongdong-gu APT_5|
|1000007|   Seoul|      Jongno-gu| true|Jongno Community ...|       10| 37.57681|   127.006|Jongno Community ...|
|1000008|   Seoul|        Jung-gu| true|Jung-gu Fashion C...|        7|37.562405|126.984377|Jung-gu Fashion C...|
|1000009|   Seoul|from other city| true|  Shincheonji Church|        8|        -|         -|Shincheonji Church_8|
|1000010|   Seoul|              -|false|     overseas inflow|      321|        -|         -|   overseas inflow_9|
|1000011|   Seoul|              -|false|contact with patient|       18|        -|         -|contact with pati...|
|1000012|   Seoul|              -|false|                 etc|       24|        -|         -|               etc_1|
|1100001|   Busan|     Dongnae-gu| true|       Onchun Church|       39| 35.21628|  129.0771|     Onchun Church_2|
|1100002|   Busan|from other city| true|  Shincheonji Church|       12|        -|         -|Shincheonji Church_3|
|1100003|   Busan|     Suyeong-gu| true|Suyeong-gu Kinder...|        5| 35.16708|  129.1124|Suyeong-gu Kinder...|
|1100004|   Busan|    Haeundae-gu| true|Haeundae-gu Catho...|        6| 35.20599|  129.1256|Haeundae-gu Catho...|
|1100005|   Busan|         Jin-gu| true|      Jin-gu Academy|        4| 35.17371|  129.0633|    Jin-gu Academy_6|
|1100006|   Busan|from other city| true|Cheongdo Daenam H...|        1|        -|         -|Cheongdo Daenam H...|
|1100007|   Busan|              -|false|     overseas inflow|       25|        -|         -|   overseas inflow_8|
|1100008|   Busan|              -|false|contact with patient|       18|        -|         -|contact with pati...|
+-------+--------+---------------+-----+--------------------+---------+---------+----------+--------------------+
only showing top 20 rows

In [0]:
cases_temp = cases.groupBy(["infection_case","salt_key"]).agg(F.sum("confirmed").alias("salt_confirmed"))
cases_temp.show()

+--------------------+--------------------+--------------+
|      infection_case|            salt_key|salt_confirmed|
+--------------------+--------------------+--------------+
|       Onchun Church|     Onchun Church_2|            39|
|Bundang Jesaeng H...|Bundang Jesaeng H...|            22|
|Cheongdo Daenam H...|Cheongdo Daenam H...|             1|
|Seosan-si Laboratory|Seosan-si Laborat...|             9|
|Bonghwa Pureun Nu...|Bonghwa Pureun Nu...|            68|
|Seosan-si Laboratory|Seosan-si Laborat...|             2|
|       Onchun Church|     Onchun Church_7|             2|
| Guro-gu Call Center|Guro-gu Call Cent...|            48|
|Goesan-gun Jangye...|Goesan-gun Jangye...|            11|
|gym facility in C...|gym facility in C...|           103|
|contact with patient|contact with pati...|            58|
|contact with patient|contact with pati...|           929|
|Geochang-gun Woon...|Geochang-gun Woon...|             8|
|Cheongdo Daenam H...|Cheongdo Daenam H...|           120|
|                 etc|               etc_1|            24|
|Daesil Convalesce...|Daesil Convalesce...|           100|
|     overseas inflow|   overseas inflow_2|            22|
|Jung-gu Fashion C...|Jung-gu Fashion C...|             7|
|Second Mi-Ju Hosp...|Second Mi-Ju Hosp...|           196|
|     overseas inflow|   overseas inflow_8|            78|
+--------------------+--------------------+--------------+
only showing top 20 rows

In [0]:
cases_answer = cases_temp.groupBy(["infection_case"]).agg(F.sum("salt_confirmed").alias("final_confirmed"))
cases_answer.show()

+--------------------+---------------+
|      infection_case|final_confirmed|
+--------------------+---------------+
|Eunpyeong St. Mar...|             14|
|Ministry of Ocean...|             30|
|Bundang Jesaeng H...|             22|
|       Milal Shelter|             36|
|       Itaewon Clubs|             81|
| Wonju-si Apartments|              3|
|       Dongan Church|             20|
|     overseas inflow|            777|
|Gyeongsan Cham Jo...|             16|
|Hansarang Convale...|            128|
|Second Mi-Ju Hosp...|            196|
|Gyeongsan Seorin ...|             66|
|Changnyeong Coin ...|              7|
|      Jin-gu Academy|              4|
|Korea Forest Engi...|              3|
|Goesan-gun Jangye...|             11|
|         Wings Tower|             10|
|     Geochang Church|             10|
|     Fatima Hospital|             37|
|Bonghwa Pureun Nu...|             68|
+--------------------+---------------+
only showing top 20 rows