In [1]:
# Link used for below exercise
# https://towardsdatascience.com/sql-window-functions-in-python-pandas-data-science-dc7c7a63cbb4

In [4]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", -1)

C:\Users\lkoturu\AppData\Local\Temp/ipykernel_15996/2270773329.py:5: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option("display.max_colwidth", -1)

## Row Number within each group (partition)

In [2]:
# The Pandas equivalent of row number within each partition with multiple sort by parameters:

# ROW_NUMBER() over (PARTITION BY ticker ORDER BY date DESC) as days_lookback
# # ---------
# ROW_NUMBER() over (PARTITION BY ticker, exchange ORDER BY date DESC, period) as example_2

In [53]:
url = "https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv"

In [60]:
df = pd.read_csv(url)

df = df.dropna()

df = df.rename(columns=str.lower).reset_index(drop=True)

In [61]:
df.head(10)

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
1,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
4,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
5,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
6,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
7,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
8,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
9,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C

In [62]:
# finding the smallest person in each gender

(
    df.assign(
        rn = df.sort_values('age')
        .groupby('sex')
        .cumcount() + 1
    )
    .sort_values(['sex', 'rn'])
    .reset_index(drop=True)
)

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,rn
0,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S,1
1,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,2
2,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S,3
3,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S,4
4,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S,5
5,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S,6
6,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S,7
7,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C,8
8,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S,9
9,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S,10
10,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)",female,17.00,1,0,PC 17758,108.9000,C65,C,11
11,312,1,1,"Ryerson, Miss. Emily Borie",female,18.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,12
12,586,1,1,"Taussig, Miss. Ruth",female,18.00,0,2,110413,79.6500,E68,S,13
13,701,1,1,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",female,18.00,1,0,PC 17757,227.5250,C62 C64,C,14
14,137,1,1,"Newsom, Miss. Helen Monypeny",female,19.00,0,2,11752,26.2833,D47,S,15
15,292,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,11967,91.0792,B49,C,16
16,888,1,1,"Graham, Miss. Margaret Edith",female,19.00,0,0,112053,30.0000,B42,S,17
17,628,1,1,"Longley, Miss. Gretchen Fiske",female,21.00,0,0,13502,77.9583,D9,S,18
18,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.00,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,19
19,357,1,1,"Bowerman, Miss. Elsie Edith",female,22.00,0,1,113505,55.0000,E33,S,20
20,540,1,1,"Frolicher, Miss. Hedwig Margaritha",female,22.00,0,2,13568,49.5000,B39,C,21
21,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.00,1,0,113776,66.6000,C2,S,22
22,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S,23
23,474,1,2,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23.00,0,0,SC/AH Basle 541,13.7917,D,C,24
24,394,1,1,"Newell, Miss. Marjorie",female,23.00,1,0,35273,113.2750,D36,C,25
25,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.00,3,2,19950,263.0000,C23 C25 C27,S,26
26,395,1,3,"Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)",female,24.00,0,2,PP 9549,16.7000,G6,S,27
27,642,1,1,"Sagesser, Mlle. Emma",female,24.00,0,0,PC 17477,69.3000,B35,C,28
28,370,1,1,"Aubart, Mme. Leontine Pauline",female,24.00,0,0,PC 17477,69.3000,B35,C,29
29,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.00,0,0,248733,13.0000,F33,S,30
30,311,1,1,"Hays, Miss. Margaret Bechstein",female,24.00,0,0,11767,83.1583,C54,C,31
31,711,1,1,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",female,24.00,0,0,PC 17482,49.5042,C90,C,32
32,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,33
33,824,1,3,"Moor, Mrs. (Beila)",female,27.00,0,1,392096,12.4750,E121,S,34
34,718,1,2,"Troutt, Miss. Edwina Celia ""Winnie""",female,27.00,0,0,34218,10.5000,E101,S,35
35,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S,36
36,252,0,3,"Strom, Mrs. Wilhelm (Elna Matilda Persson)",female,29.00,1,1,347054,10.4625,G6,S,37
37,731,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,38
38,521,1,1,"Perreault, Miss. Anne",female,30.00,0,0,12749,93.5000,B73,S,39
39,258,1,1,"Cherry, Miss. Gladys",female,30.00,0,0,110152,86.5000,B77,S,40
40,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.00,0,0,PC 17485,56.9292,E36,C,41
41,319,1,1,"Wick, Miss. Mary Natalie",female,31.00,0,2,36928,164.8667,C7,S,42
42,216,1,1,"Newell, Miss. Madeleine",female,31.00,1,0,35273,113.2750,D36,C,43
43,219,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,11813,76.2917,D15,C,44
44,124,1,2,"Webber, Miss. Susan",female,32.50,0,0,27267,13.0000,E101,S,45
45,760,1,1,"Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)",female,33.00,0,0,110152,86.5000,B77,S,46
46,810,1,1,"Chambers, Mrs. Norman Campbell (Bertha Griggs)",female,33.00,1,0,113806,53.1000,E8,S,47
47,413,1,1,"Minahan, Miss. Daisy E",female,33.00,1,0,19928,90.0000,C78,Q,48
48,517,1,2,"Lemore, Mrs. (Amelia Milley)",female,34.00,0,0,C.A. 34260,10.5000,F33,S,49
49,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S,50
50,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S,51
51,231,1,1,"Harris, Mrs. Henry Birkhardt (Irene Wallach)",female,35.00,1,0,36973,83.4750,C83,S,52
52,487,1,1,"Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)",female,35.00,1,0,19943,90.0000,C93,S,53
53,764,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.00,1,2,113760,120.0000,B96 B98,S,54
54,541,1,1,"Crosby, Miss. Harriet R",female,36.00,0,2,WE/P 5735,71.0000,B22,S,55
55,326,1,1,"Young, Miss. Marie Grice",female,36.00,0,0,PC 17760,135.6333,C32,C,56
56,328,1,2,"Ball, Mrs. (Ada E Hall)",female,36.00,0,0,28551,13.0000,D,S,57
57,717,1,1,"Endres, Miss. Caroline Louise",female,38.00,0,0,PC 17757,227.5250,C45,C,58
58,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.00,1,0,PC 17599,71.2833,C85,C,59
59,836,1,1,"Compton, Miss. Sara Rebecca",female,39.00,1,1,PC 17756,83.1583,E49,C,60
60,559,1,1,"Taussig, Mrs. Emil (Tillie Mandelbaum)",female,39.00,1,1,110413,79.6500,E67,S,61
61,578,1,1,"Silvey, Mrs. William Baird (Alice Munger)",female,39.00,1,0,13507,55.9000,E44,S,62
62,582,1,1,"Thayer, Mrs. John Borland (Marian Longstreth Morris)",female,39.00,1,1,17421,110.8833,C68,C,63
63,610,1,1,"Shutes, Miss. Elizabeth W",female,40.00,0,0,PC 17582,153.4625,C125,S,64
64,320,1,1,"Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)",female,40.00,1,1,16966,134.5000,E34,C,65
65,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C,66
66,780,1,1,"Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)",female,43.00,0,1,24160,211.3375,B3,S,67
67,524,1,1,"Hippach, Mrs. Louis Albert (Ida Sophia Fischer)",female,44.00,0,1,111361,57.9792,B18,C,68
68,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.00,0,0,PC 17610,27.7208,B4,C,69
69,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.00,1,1,11751,52.5542,D35,S,70
70,557,1,1,"Duff Gordon, Lady. (Lucille Christiana Sutherland) (""Mrs Morgan"")",female,48.00,1,0,11755,39.6000,A16,C,71
71,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Barron)",female,48.00,0,0,17466,25.9292,D17,S,72
72,797,1,1,"Leader, Dr. Alice (Farnham)",female,49.00,0,0,17465,25.9292,D17,S,73
73,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C,74
74,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C,75
75,178,0,1,"Isham, Miss. Ann Elizabeth",female,50.00,0,0,PC 17595,28.7125,C49,C,76
76,766,1,1,"Hogeboom, Mrs. John C (Anna Andrews)",female,51.00,1,0,13502,77.9583,D11,S,77
77,592,1,1,"Stephenson, Mrs. Walter Bertram (Martha Eustis)",female,52.00,1,0,36947,78.2667,D20,C,78
78,821,1,1,"Hays, Mrs. Charles Melville (Clara Jennings Gregg)",female,52.00,1,1,12749,93.5000,B69,S,79
79,572,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.00,2,0,11769,51.4792,C101,S,80
80,497,1,1,"Eustis, Miss. Elizabeth Mussey",female,54.00,1,0,36947,78.2667,D20,C,81
81,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.00,0,1,11767,83.1583,C50,C,82
82,773,0,2,"Mack, Mrs. (Mary)",female,57.00,0,0,S.O./P.P. 3,10.5000,E77,S,83
83,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S,84
84,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.00,0,1,PC 17582,153.4625,C125,S,85
85,196,1,1,"Lurette, Miss. Elise",female,58.00,0,0,PC 17569,146.5208,B80,C,86
86,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.00,1,0,110813,75.2500,D37,C,87
87,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.00,1,0,13502,77.9583,D7,S,88
88,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,1
89,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S,2
90,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S,3
91,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S,4
92,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S,5
93,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S,6
94,803,1,1,"Carter, Master. William Thornton II",male,11.00,1,2,113760,120.0000,B96 B98,S,7
95,551,1,1,"Thayer, Mr. John Borland Jr",male,17.00,0,2,17421,110.8833,C70,C,8
96,506,0,1,"Penasco y Castellana, Mr. Victor de Satode",male,18.00,1,0,PC 17758,108.9000,C65,C,9
97,716,0,3,"Soholt, Mr. Peter Andreas Lauritz Andersen",male,19.00,0,0,348124,7.6500,F G73,S,10
98,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S,11
99,749,0,1,"Marvin, Mr. Daniel Warner",male,19.00,1,0,113773,53.1000,D30,S,12
100,103,0,1,"White, Mr. Richard Frasar",male,21.00,0,1,35281,77.2875,D26,S,13
101,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,63.3583,D10 D12,C,14
102,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C,15
103,140,0,1,"Giglio, Mr. Victor",male,24.00,0,0,PC 17593,79.2000,B86,C,16
104,485,1,1,"Bishop, Mr. Dickinson H",male,25.00,1,0,11967,91.0792,B49,C,17
105,371,1,1,"Harder, Mr. George Achilles",male,25.00,1,0,11765,55.4417,E50,C,18
106,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S,19
107,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C,20
108,682,1,1,"Hassab, Mr. Hammad",male,27.00,0,0,PC 17572,76.7292,D49,C,21
109,378,0,1,"Widener, Mr. Harry Elkins",male,27.00,0,2,113503,211.5000,C82,C,22
110,725,1,1,"Chambers, Mr. Norman Campbell",male,27.00,1,0,113806,53.1000,E8,S,23
111,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.00,0,0,110564,26.5500,C52,S,24
112,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S,25
113,783,0,1,"Long, Mr. Milton Clyde",male,29.00,0,0,113501,30.0000,D6,S,26
114,337,0,1,"Pears, Mr. Thomas Clinton",male,29.00,1,0,113776,66.6000,C2,S,27
115,453,0,1,"Foreman, Mr. Benjamin Laventall",male,30.00,0,0,113051,27.7500,C111,C,28
116,672,0,1,"Davidson, Mr. Thornton",male,31.00,1,0,F.C. 12750,52.0000,B71,S,29
117,691,1,1,"Dick, Mr. Albert Adrian",male,31.00,1,0,17474,57.0000,B20,S,30
118,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.00,0,0,PC 17590,50.4958,A24,S,31
119,633,1,1,"Stahelin-Maeglin, Dr. Max",male,32.00,0,0,13214,30.5000,B50,C,32
120,430,1,3,"Pickard, Mr. Berk (Berk Trembisky)",male,32.00,0,0,SOTON/O.Q. 392078,8.0500,E10,S,33
121,873,0,1,"Carlsson, Mr. Frans Olof",male,33.00,0,0,695,5.0000,B51 B53 B55,S,34
122,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S,35
123,738,1,1,"Lesurer, Mr. Gustave J",male,35.00,0,0,PC 17755,512.3292,B101,C,36
124,702,1,1,"Silverthorne, Mr. Spencer Victor",male,35.00,0,0,PC 17475,26.2875,E24,S,37
125,513,1,1,"McGough, Mr. James Robert",male,36.00,0,0,PC 17473,26.2875,E25,S,38
126,742,0,1,"Cavendish, Mr. Tyrell William",male,36.00,1,0,19877,78.8500,C46,S,39
127,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.00,0,1,PC 17755,512.3292,B51 B53 B55,C,40
128,573,1,1,"Flynn, Mr. John Irwin (""Irving"")",male,36.00,0,0,PC 17474,26.3875,E25,S,41
129,584,0,1,"Ross, Mr. John Hugo",male,36.00,0,0,13049,40.1250,A10,C,42
130,391,1,1,"Carter, Mr. William Ernest",male,36.00,1,2,113760,120.0000,B96 B98,S,43
131,293,0,2,"Levy, Mr. Rene Jacques",male,36.00,0,0,SC/Paris 2163,12.8750,D,C,44
132,149,0,2,"Navratil, Mr. Michel (""Louis M Hoffman"")",male,36.50,0,2,230080,26.0000,F2,S,45
133,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,1,1,11751,52.5542,D35,S,46
134,138,0,1,"Futrelle, Mr. Jacques Heath",male,37.00,1,0,113803,53.1000,C123,S,47
135,274,0,1,"Natsch, Mr. Charles H",male,37.00,0,1,PC 17596,29.7000,C118,C,48
136,333,0,1,"Graham, Mr. George Edward",male,38.00,0,1,PC 17582,153.4625,C91,S,49
137,225,1,1,"Hoyt, Mr. Frederick Maxfield",male,38.00,1,0,19943,90.0000,C93,S,50
138,807,0,1,"Andrews, Mr. Thomas Jr",male,39.00,0,0,112050,0.0000,A36,S,51
139,264,0,1,"Harrison, Mr. William",male,40.00,0,0,112059,0.0000,B94,S,52
140,210,1,1,"Blank, Mr. Henry",male,40.00,0,0,112277,31.0000,A31,C,53
141,708,1,1,"Calderhead, Mr. Edward Pennington",male,42.00,0,0,PC 17476,26.2875,E24,S,54
142,622,1,1,"Kimball, Mr. Edwin Nelson Jr",male,42.00,1,0,11753,52.5542,D19,S,55
143,700,0,3,"Humblen, Mr. Adolf Mathias Nicolai Olsen",male,42.00,0,0,348121,7.6500,F G63,S,56
144,246,0,1,"Minahan, Dr. William Edward",male,44.00,2,0,19928,90.0000,C78,Q,57
145,537,0,1,"Butt, Major. Archibald Willingham",male,45.00,0,0,113050,26.5500,B38,S,58
146,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S,59
147,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.00,0,0,113784,35.5000,T,S,60
148,332,0,1,"Partner, Mr. Austen",male,45.50,0,0,113043,28.5000,C124,S,61
149,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S,62
150,790,0,1,"Guggenheim, Mr. Benjamin",male,46.00,0,0,PC 17593,79.2000,B82 B84,C,63
151,663,0,1,"Colley, Mr. Edward Pomeroy",male,47.00,0,0,5727,25.5875,E58,S,64
152,111,0,1,"Porter, Mr. Walter Chamberlain",male,47.00,0,0,110465,52.0000,C110,S,65
153,463,0,1,"Gee, Mr. Arthur H",male,47.00,0,0,111320,38.5000,E63,S,66
154,516,0,1,"Walker, Mr. William Anderson",male,47.00,0,0,36967,34.0208,D46,S,67
155,461,1,1,"Anderson, Mr. Harry",male,48.00,0,0,19952,26.5500,E12,S,68
156,713,1,1,"Taylor, Mr. Elmer Zebley",male,48.00,1,0,19996,52.0000,C126,S,69
157,646,1,1,"Harper, Mr. Henry Sleeper",male,48.00,1,0,PC 17572,76.7292,D33,C,70
158,699,0,1,"Thayer, Mr. John Borland",male,49.00,1,1,17421,110.8833,C68,C,71
159,454,1,1,"Goldenberg, Mr. Samuel L",male,49.00,1,0,17453,89.1042,C92,C,72
160,600,1,1,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.00,1,0,PC 17485,56.9292,A20,C,73
161,545,0,1,"Douglas, Mr. Walter Donald",male,50.00,1,0,PC 17761,106.4250,C86,C,74
162,435,0,1,"Silvey, Mr. William Baird",male,50.00,1,0,13507,55.9000,E44,S,75
163,858,1,1,"Daly, Mr. Peter Denis",male,51.00,0,0,113055,26.5500,E17,S,76
164,450,1,1,"Peuchen, Major. Arthur Godfrey",male,52.00,0,0,113786,30.5000,C104,S,77
165,263,0,1,"Taussig, Mr. Emil",male,52.00,1,1,110413,79.6500,E67,S,78
166,125,0,1,"White, Mr. Percival Wayland",male,54.00,0,1,35281,77.2875,D26,S,79
167,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S,80
168,493,0,1,"Molson, Mr. Harry Markland",male,55.00,0,0,113787,30.5000,C30,S,81
169,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.00,0,0,13213,35.5000,A26,C,82
170,175,0,1,"Smith, Mr. James Clinch",male,56.00,0,0,17764,30.6958,A7,C,83
171,488,0,1,"Kent, Mr. Edward Austin",male,58.00,0,0,11771,29.7000,B37,C,84
172,660,0,1,"Newell, Mr. Arthur Webster",male,58.00,0,2,35273,113.2750,D48,C,85
173,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.00,1,1,13567,79.2000,B41,C,86
174,626,0,1,"Sutton, Mr. Frederick",male,61.00,0,0,36963,32.3208,D50,S,87
175,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.00,0,0,111240,33.5000,B19,S,88
176,253,0,1,"Stead, Mr. William Thomas",male,62.00,0,0,113514,26.5500,C87,S,89
177,439,0,1,"Fortune, Mr. Mark",male,64.00,1,4,19950,263.0000,C23 C25 C27,S,90
178,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C,91
179,457,0,1,"Millet, Mr. Francis Davis",male,65.00,0,0,13509,26.5500,E38,S,92
180,746,0,1,"Crosby, Capt. Edward Gifford",male,70.00,1,1,WE/P 5735,71.0000,B22,S,93
181,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C,94
182,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000,A23,S,95

In [63]:
# LAG(price) over (PARTITION BY ticker ORDER BY date) as last_day_px
# ---------
# LEAD(price) over (PARTITION BY ticker ORDER BY date) as next_day_px

In [64]:
# df['last_day_px'] = df.sort_values(by=['date'], ascending=True).groupby(['ticker'])['price'].shift(1)
# ---------
# df['next_day_px'] = df.sort_values(by=['date'], ascending=True).groupby(['ticker'])['price'].shift(-1)

In [65]:
# PERCENT_RANK() OVER (PARTITION BY ticker, year ORDER BY price) as perc_price

# df['perc_price'] = df.groupby(['ticker', 'year'])['price'].rank(pct=True)

In [66]:
# AVG(trade_vol) OVER (PARTITION BY ticker) as avg_trade_vol
# # ---------
# AVG(price) OVER (PARTITION BY ticker ORDER BY date ROWS BETWEEN 19 PRECEDING AND CURRENT ROW) as ma20

# df['avg_trade_vol'] = df.groupby(['ticker', 'year'])['trade_vol']\
#                         .transform('mean')
# ---------
# df['ma20'] = df.sort_values(by=['date'], ascending=True)\
#                     .groupby('ticker')['price']\
#                     .rolling(20, min_periods = 1).mean()\
#                     .reset_index(drop=True, level=0)